### ISSUE TITLE
[Error] Upon server start

### ISSUE THREAD

**Issue by LaFesta1749** [Simyon264/AntiSurfaceCamping#1] opened 2023-09-15 16:10 UTC
_Using Exiled: 8.2.1
This plugin: 1.1.0_

**Here's the error messages:**

```
[2023-09-15 18:08:54.262 +02:00] [ERROR] [Exiled.Loader] Error while initializing plugin AntiSurfaceCamping (at )! System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'AntiSurfaceCamping.Plugin' threw an exception. ---> System.TypeLoadException: Could not load type of field 'AntiSurfaceCamping.Config:<immuneRoles>k__BackingField' (11) due to: Could not resolve type with token 01000016 from typeref (expected class 'RoleType' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:RoleType member:(null)
                                   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00029] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Activator.CreateInstance[T] () [0x00015] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at Exiled.API.Features.Plugin`1[TConfig]..ctor () [0x00069] in <ccbd55689f2843f2bda6888cb71fd368>:0 
                                   at AntiSurfaceCamping.Plugin..ctor () [0x00050] in <9c5fb39a7fa640ecaaa76edeafed0578>:0 
                                   at AntiSurfaceCamping.Plugin..cctor () [0x00000] in <9c5fb39a7fa640ecaaa76edeafed0578>:0 
                                    --- End of inner exception stack trace ---
                                   at System.Reflection.RuntimePropertyInfo.StaticGetterAdapterFrame[R] (System.Reflection.RuntimePropertyInfo+StaticGetter`1[R] getter, System.Object obj) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Reflection.RuntimePropertyInfo.GetValue (System.Object obj, System.Object[] index) [0x0006c] in <05089c1b6989455fb1452c627044bac4>:0 
                                    --- End of inner exception stack trace ---
                                   at System.Reflection.RuntimePropertyInfo.GetValue (System.Object obj, System.Object[] index) [0x00080] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at System.Reflection.PropertyInfo.GetValue (System.Object obj) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0 
                                   at Exiled.Loader.Loader.CreatePlugin (System.Reflection.Assembly assembly) [0x00119] in <e50966ad59b94987b8c6651c9f3d0ecb>:0
```

**And this one also (not using Custom Roles):**

```
[2023-09-15 18:08:54.440 +02:00] [ERROR] [Exiled.CustomRoles] Error loading types for AntiSurfaceCamping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. It can be ignored if it's not using Exiled.CustomRoles.
```

**Comment by Simyon264** [comment] 2023-09-15 17:15
Interesting, mind sending me the config for ASC you currently have?

**Comment by LaFesta1749** [comment] 2023-09-16 10:44
> Interesting, mind sending me the config for ASC you currently have?

![image](https://github.com/Simyon264/AntiSurfaceCamping/assets/1494298/d3dbc151-e88c-47c3-a742-39735b493967)

There is not config generated for the AntiSurfaceCamping as it doesn't even load to generate themself.

**Comment by Simyon264** [comment] 2023-09-16 12:11
I uploaded the wrong .dll file in the release. The issue is now fixed. Just download the new .dll file from the release.

**Closed as completed by Simyon264** 2023-09-16 12:11 UTC

**Comment by LaFesta1749** [comment] 2023-09-16 12:39
Thank you. It's working now.
